#######################################################################################
# Book settings
title : Synestias — An Interactive Primer
author: Gigja O. Hollyday (edited by S. T. Stewart)
logo: 'synestia.png'

# Information about where the book exists on the web
description: >-
  Educational Visualization Tools for Conveying Research: Jupyter Notebooks on Synestias

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/ststewart/synestiabook2
  path_to_book                : "synestia-book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

html:
  google_analytics_id: UA-15464495-6
